-- 创建独立的假期类型表
CREATE TABLE leave_type (
    leave_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name VARCHAR2(50) NOT NULL UNIQUE,
    description VARCHAR2(200)
);

-- 预置假期类型数据
INSERT INTO leave_type (type_name, description) VALUES ('Vacation', '年假/带薪假期');
INSERT INTO leave_type (type_name, description) VALUES ('Mandatory', '法定强制假期');
INSERT INTO leave_type (type_name, description) VALUES ('Family/child care', '家庭/育儿假');
INSERT INTO leave_type (type_name, description) VALUES ('Medical', '病假');
INSERT INTO leave_type (type_name, description) VALUES ('Health Screening', '体检假');
INSERT INTO leave_type (type_name, description) VALUES ('Training', '培训假');
INSERT INTO leave_type (type_name, description) VALUES ('Biz Trip', '出差');
INSERT INTO leave_type (type_name, description) VALUES ('WFH', '居家办公');
INSERT INTO leave_type (type_name, description) VALUES ('Volunteer', '志愿者假');
INSERT INTO leave_type (type_name, description) VALUES ('Birthday Month', '生日假');

-- 员工信息表
CREATE TABLE staff (
    staff_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_name VARCHAR2(100) NOT NULL,
    is_manager CHAR(1) DEFAULT 'N',
    created_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_time TIMESTAMP
);

-- 假期申请表（含审计字段）
CREATE TABLE leave_application (
    application_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_name VARCHAR2(100) NOT NULL,
    leave_type_id NUMBER NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    hours_taken NUMBER(5,2) NOT NULL,
    manager_approved CHAR(1) DEFAULT 'N',
    application_manager_name VARCHAR2(100),
    location_during_leave VARCHAR2(200),
    -- 审计字段
    created_by VARCHAR2(100) DEFAULT USER,
    created_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by VARCHAR2(100),
    updated_time TIMESTAMP,
    -- 业务字段
    remarks VARCHAR2(500)
);

-- 附件表
CREATE TABLE leave_attachment (
    attachment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id NUMBER NOT NULL,
    file_name VARCHAR2(255) NOT NULL,
    file_size NUMBER,
    file_type VARCHAR2(50),
    storage_path VARCHAR2(500) NOT NULL,
    upload_time TIMESTAMP DEFAULT SYSTIMESTAMP,
    upload_by VARCHAR2(100) DEFAULT USER
);

-- 创建索引
CREATE INDEX idx_leave_app_staff ON leave_application(staff_name);
CREATE INDEX idx_leave_app_type ON leave_application(leave_type_id);
CREATE INDEX idx_leave_app_dates ON leave_application(start_date, end_date);